apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  registries.conf: |
    registries:
    - name: GitHub
      prefix: ghcr.io
      api_url: https://ghcr.io
      credentials: pullsecret:default/dockerconfigjson-github-com
      default: true
