apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  log.level: debug
  registries.conf: |
    registries:
    - name: GitHub
      prefix: ghcr.io
      api_url: https://ghcr.io
      credentials: pullsecret:argocd/dockerconfigjson-github-com
      insecure: true
    - name: Docker Hub
      prefix: docker.io
      api_url: https://registry.hub.docker.com
      credentials: pullsecret:argocd/dockerconfigjson-github-com
      default: true
