apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: marco-applicationset
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          # name is name for application, must be same for all elements
          - server: https://kubernetes.default.svc
            name: marco
            branch: marco-argocd

  template:
    # argocd application specification

    metadata:
      name: "{{ name }}-{{ branch }}"
      namespace: argocd
      annotations:
        argocd-image-updater.argoproj.io/image-list: "{{ name }}=ghcr.io/moonchel/argocd-helm-release-flow:{{ branch }}"
        "argocd-image-updater.argoproj.io/{{ name }}.update-strategy": digest
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/myalias.force-update: "true"

    spec:
      project: default

      source:
        repoURL: https://github.com/MoonChel/argocd-helm-release-flow.git
        targetRevision: "{{ branch }}"
        path: applications/world

      destination:
        server: "{{ server }}"
        namespace: "{{ name }}-{{ branch }}"

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: false
