apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: world
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MoonChel/argocd-helm-release-flow.git
    targetRevision: HEAD
    path: applications/world

  destination:
    server: https://kubernetes.default.svc
    namespace: default
