apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: world
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: world=ghcr.io/moonchel/argocd-helm-release-flow:master
    argocd-image-updater.argoproj.io/world.update-strategy: digest
    argocd-image-updater.argoproj.io/myalias.force-update: "true"

spec:
  project: default
  source:
    repoURL: https://github.com/MoonChel/argocd-helm-release-flow.git
    targetRevision: world-argocd
    path: applications/world

  destination:
    server: https://kubernetes.default.svc
    namespace: default
